### ISSUE TITLE
Show more than 100 forks

### ISSUE THREAD

**Issue by dhoerl** [lukaszmn/active-forks#14]
Don't know JavaScript and can't add paging myself. The original repository is unmaintained, I see you did some work lately. maybe this wouldn't be hard to add.

I am trying to drill down on a repository that has 570 forks!

**Comment by lukaszmn** [comment]
Hi, sorry you had to wait. I updated the documentation and posted the "application" - the link is on the main page: https://lukaszmn.github.io/active-forks/index.html.

As for increasing the amount, provide your Auth token, expand Options and set Max Records to 600.

**Comment by dhoerl** [comment]
Thank you!
